# Generated by Django 4.1.6 on 2023-12-14 03:07

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="code",
            field=models.CharField(
                default=api.models.generate_unique_code, max_length=10, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="host",
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
